package pro.eng.yui.oss.osm.jppostaldata;

import pro.eng.yui.oss.osm.jppostaldata.worker.BoundaryDataGenerator;
import pro.eng.yui.oss.osm.jppostaldata.worker.CityAndSuburbDataGenerator;
import pro.eng.yui.oss.osm.jppostaldata.worker.PrefectureDataJsonGenerator;
import tools.jackson.databind.JsonNode;
import tools.jackson.databind.ObjectMapper;

import java.io.IOException;
import java.io.InputStream;
import java.net.URI;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.nio.file.StandardCopyOption;
import java.time.LocalDateTime;
import java.time.ZoneId;
import java.time.ZonedDateTime;
import java.time.format.DateTimeFormatter;
import java.util.*;

public class Main {
    
    public static final ZoneId JST = ZoneId.of("Asia/Tokyo");
    public static final DateTimeFormatter FORMATTER = DateTimeFormatter.ofPattern("y/MM/dd'T'HH:mm:ss");

    public static void main(String[] args) {
        System.out.println("定期実行開始: " + FORMATTER.format(ZonedDateTime.now(JST)));

        boolean runBoundary = false;
        boolean runCity = false;
        String targetPrefecture = null;

        for (String arg : args) {
            if (arg == null || arg.isBlank()) {
                continue;
            }
            if ("--boundary".equals(arg)) {
                runBoundary = true;
            } else if ("--city".equals(arg)) {
                runCity = true;
            } else {
                if (targetPrefecture != null) {
                    throw new IllegalArgumentException("引数には都道府県コードまたは都道府県名を1つだけ指定してください");
                }
                targetPrefecture = arg.trim();
            }
        }

        if (runBoundary) {
            try {
                new BoundaryDataGenerator().generate();
            } catch (IOException e) {
                System.err.println("boundary.jsonの生成に失敗しました");
                e.printStackTrace();
            }
        }

        if (runCity) {
            try {
                new CityAndSuburbDataGenerator().generate();
            } catch (IOException e) {
                System.err.println("cityAndSuburb.jsonの生成に失敗しました");
                e.printStackTrace();
            }
        }

        try {
            generateJson(targetPrefecture);
        } catch (IOException e) {
            System.err.println("ファイルの生成に失敗しました");
            e.printStackTrace();
        }

        System.out.println("定期実行終了: " + FORMATTER.format(ZonedDateTime.now(JST)));
        
    }

    private static void generateJson(String targetPrefecture) throws IOException {
        ObjectMapper mapper = new ObjectMapper();

        // 保存先ディレクトリの確認
        Path outputDir = Paths.get("pages");
        if (!Files.exists(outputDir)) {
            Files.createDirectories(outputDir);
        }

        // データ更新バッチ
        List<PrefectureDataJsonGenerator.ResultTimestamp> prefTimestamp = loadExistPrefTimestamp();
        Set<PrefectureDataJsonGenerator.Result> results = generatePrefectureDataJson(targetPrefecture);
        
        // ファイル書き出し
        Path outputDataDir = outputDir.resolve("data");
        Files.createDirectories(outputDataDir);

        for (PrefectureDataJsonGenerator.Result r : results) {
            final String prefCode = String.format("%02d",r.getPrefCode());
            final String fileName;
            final String resultTimestampCode;
            if (r.getSubCode() != null) {
                fileName = "jPostal_"+ prefCode + "_" + r.getSubCode() + ".json";
                resultTimestampCode = prefCode + "_" + r.getSubCode();
            } else {
                fileName = "jPostal_"+ prefCode +".json";
                resultTimestampCode = prefCode;
            }
            Path dataOutputPath = outputDataDir.resolve(fileName);
            mapper.writeValue(dataOutputPath.toFile(), r.getObjects());
            
            for (int i=0; i<prefTimestamp.size(); i++) {
                if (prefTimestamp.get(i).code.equals(resultTimestampCode)) {
                    prefTimestamp.remove(i);
                    break;
                }
            }
            prefTimestamp.add(
                new PrefectureDataJsonGenerator.ResultTimestamp(resultTimestampCode, r.getPrefName(), r.getDataTimestamp(), r.getDataSize())
            );
        }

        Map<String, Object> data = new HashMap<>();
        data.put("lastUpdated", FORMATTER.format(ZonedDateTime.now(JST)));
        data.put("status", "OK");
        data.put("message", "Generated by Java Main method");
        
        data.put("prefectures", prefTimestamp);
        Path outputPath = outputDataDir.resolve("date.json");
        mapper.writeValue(outputPath.toFile(), data);
        System.out.println("JSONを生成しました: " + outputPath.toAbsolutePath());
        
        Path indexOutputPath = outputDir.resolve("index.html");
        try (InputStream inputStream = Main.class.getResourceAsStream("/content/index.html")) {
            if (inputStream == null) {
                throw new IOException("index.htmlが見つかりません");
            }
            Files.copy(inputStream, indexOutputPath, StandardCopyOption.REPLACE_EXISTING);
            System.out.println("index.htmlをコピーしました: " + indexOutputPath.toAbsolutePath());
        }
        Path faviconOutputPath = outputDir.resolve("favicon.png");
        try (InputStream inputStream = Main.class.getResourceAsStream("/content/favicon.png")) {
            if (inputStream == null) {
                throw new IOException("favicon.pngが見つかりません");
            }
            Files.copy(inputStream, faviconOutputPath, StandardCopyOption.REPLACE_EXISTING);
            System.out.println("favicon.pngをコピーしました: " + faviconOutputPath.toAbsolutePath());
        }

        Path masterDir = outputDir.resolve("master");
        if (!Files.exists(masterDir)) {
            Files.createDirectories(masterDir);
        }
        Path prefOutputPath = masterDir.resolve("pref.json");
        try (InputStream inputStream = Main.class.getResourceAsStream("/content/master/pref.json")) {
            if (inputStream == null) {
                throw new IOException("pref.jsonが見つかりません");
            }
            Files.copy(inputStream, prefOutputPath, StandardCopyOption.REPLACE_EXISTING);
            System.out.println("pref.jsonをコピーしました: " + prefOutputPath.toAbsolutePath());
        }
        Path masterSubDir = masterDir.resolve("sub");
        if (!Files.exists(masterSubDir)) {
            Files.createDirectories(masterSubDir);
        }
        Path sub01OutputPath = masterSubDir.resolve("01.json");
        try (InputStream inputStream = Main.class.getResourceAsStream("/content/master/sub/01.json")) {
            if (inputStream == null) {
                throw new IOException("sub/01.jsonが見つかりません");
            }
            Files.copy(inputStream, sub01OutputPath, StandardCopyOption.REPLACE_EXISTING);
            System.out.println("sub/01.jsonをコピーしました: " + sub01OutputPath.toAbsolutePath());
        }
    }

    private static Set<PrefectureDataJsonGenerator.Result> generatePrefectureDataJson(String targetPrefecture) throws IOException {
        PrefectureDataJsonGenerator generator = new PrefectureDataJsonGenerator();
        Set<PrefectureDataJsonGenerator.Result> resultSet = new HashSet<>();
        
        ObjectMapper mapper = new ObjectMapper();
        JsonNode prefArray;
        try (InputStream inputStream = Main.class.getResourceAsStream("/content/master/pref.json")) {
            prefArray = mapper.readTree(inputStream);
        }

        boolean targetFound = targetPrefecture == null;

        for (JsonNode node : prefArray) {
            String prefName = node.get("name").asText();
            int prefCode = 0;
            JsonNode codeNode = node.get("code");
            if (codeNode.isNumber()) {
                prefCode = codeNode.asInt();
            } else if (codeNode.isTextual()) {
                prefCode = Integer.parseInt(codeNode.asText());
            }
            String subAreaCode = node.has("sub") ? node.get("sub").asText() : null;

            if (targetPrefecture != null
                    && !targetPrefecture.equals(prefName)
                    && !targetPrefecture.equals(String.valueOf(prefCode))
                    && !targetPrefecture.equals(String.format("%02d", prefCode))) {
                continue;
            }
            targetFound = true;

            if (subAreaCode != null) {
                // サブエリア設定がある場合
                // 1. 本体の空データ (data部分を空にして残す)
                Map<String, Object> emptyData = new HashMap<>();
                LocalDateTime timestamp = LocalDateTime.now(JST);
                emptyData.put("lastModified", timestamp.format(FORMATTER));
                emptyData.put("prefectureCode", prefCode);
                emptyData.put("prefectureName", prefName);
                emptyData.put("data", Collections.emptyList());
                resultSet.add(new PrefectureDataJsonGenerator.Result(prefCode, prefName, timestamp, emptyData));

                // 2. サブエリアごとのデータ取得
                JsonNode subArray;
                try (InputStream subIs = Main.class.getResourceAsStream("/content/master/sub/"+ subAreaCode +".json")) {
                    subArray = mapper.readTree(subIs);
                }
                for (JsonNode subNode : subArray) {
                    String subCode = subNode.get("code").asText();
                    int adminLevel = subNode.get("admin_level").asInt();
                    String subName = subNode.get("name").asText();
                    try {
                        PrefectureDataJsonGenerator.Result result =
                                generator.generate(prefCode, subCode, adminLevel, subName);
                        System.out.println(FORMATTER.format(ZonedDateTime.now(JST)) +
                                subName + " 処理完了。件数: " + result.getDataSize());
                        resultSet.add(result);
                    } catch (IOException | IllegalStateException ioe) {
                        System.err.println(FORMATTER.format(ZonedDateTime.now(JST)) +
                                subName + " 処理失敗:" + ioe.getMessage());
                    }
                }
            } else {
                // サブエリア設定がない場合
                try {
                    PrefectureDataJsonGenerator.Result result =
                            generator.generate(prefCode, prefName);
                    System.out.println(FORMATTER.format(ZonedDateTime.now(JST)) +
                            prefName + " 処理完了。件数: " + result.getDataSize());
                    resultSet.add(result);
                } catch (IOException | IllegalStateException ioe) {
                    System.err.println(FORMATTER.format(ZonedDateTime.now(JST)) +
                            prefName + " 処理失敗:" + ioe.getMessage());
                }
            }
        }

        if (!targetFound) {
            throw new IllegalArgumentException("都道府県コードまたは都道府県名が不正です: " + targetPrefecture);
        }

        return resultSet;
    }
    
    private static List<PrefectureDataJsonGenerator.ResultTimestamp> loadExistPrefTimestamp(){
        List<PrefectureDataJsonGenerator.ResultTimestamp> prefectures = new ArrayList<>();

        try (HttpClient client = HttpClient.newBuilder().build()){
            HttpRequest request = HttpRequest.newBuilder()
                    .uri(URI.create("https://yui-kitamura.github.io/OsmJpPostalMapDataSource/data/date.json"))
                    .GET()
                    .build();

            HttpResponse<String> response = client.send(request, HttpResponse.BodyHandlers.ofString());

            ObjectMapper mapper = new ObjectMapper();
            JsonNode jsonData = mapper.readTree(response.body());
            JsonNode arrayData = jsonData.get("prefectures");
            
            if (arrayData != null && arrayData.isArray()) {
                for (JsonNode obj : arrayData) {
                    String name = obj.path("name").asText();
                    String code = obj.path("code").asText();
                    
                    String lastModStr = obj.path("lastModified").asText();
                    if (name.isEmpty() || lastModStr.isEmpty()) {
                        continue;
                    }
                    LocalDateTime timestamp = LocalDateTime.from(FORMATTER.parse(lastModStr));
                    int objectCount = obj.path("objectCount").asInt();
                    prefectures.add(new PrefectureDataJsonGenerator.ResultTimestamp(code, name, timestamp, objectCount));
                }
            }
        }catch (IOException | InterruptedException ignore) { }
        return prefectures;
    }
}
