package pro.eng.yui.oss.osm.jppostaldata;

import com.google.gson.Gson;
import com.google.gson.JsonArray;
import com.google.gson.JsonObject;
import pro.eng.yui.oss.osm.jppostaldata.worker.PrefectureDataJsonGenerator;
import tools.jackson.databind.JsonNode;
import tools.jackson.databind.ObjectMapper;

import java.io.IOException;
import java.io.InputStream;
import java.net.URI;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.nio.file.StandardCopyOption;
import java.time.LocalDateTime;
import java.time.ZoneId;
import java.time.ZonedDateTime;
import java.time.format.DateTimeFormatter;
import java.util.*;

public class Main {
    
    public static final ZoneId JST = ZoneId.of("Asia/Tokyo");
    public static final DateTimeFormatter FORMATTER = DateTimeFormatter.ofPattern("y/MM/dd'T'HH:mm:ss");
    
    public static void main(String[] args) {
        System.out.println("定期実行開始: " + FORMATTER.format(ZonedDateTime.now(JST)));

        if (args.length > 1) {
            throw new IllegalArgumentException("引数には都道府県コードまたは都道府県名を1つだけ指定してください");
        }
        String targetPrefecture = args.length == 0 || args[0].isBlank() ? null : args[0].trim();
        
        try {
            generateJson(targetPrefecture);
        } catch (IOException e) {
            System.err.println("ファイルの生成に失敗しました");
            e.printStackTrace();
        }

        System.out.println("定期実行終了: " + FORMATTER.format(ZonedDateTime.now(JST)));
        
    }

    private static void generateJson(String targetPrefecture) throws IOException {
        ObjectMapper mapper = new ObjectMapper();

        // 保存先ディレクトリの確認
        Path outputDir = Paths.get("pages");
        if (!Files.exists(outputDir)) {
            Files.createDirectories(outputDir);
        }

        // データ更新バッチ
        List<PrefectureDataJsonGenerator.ResultTimestamp> prefTimestamp = loadExistPrefTimestamp();
        Set<PrefectureDataJsonGenerator.Result> results = generatePrefectureDataJson(targetPrefecture);
        
        // ファイル書き出し
        Path outputDataDir = outputDir.resolve("data");
        Files.createDirectories(outputDataDir);

        for (PrefectureDataJsonGenerator.Result r : results) {
            final int prefCode = r.getPrefCode();
            final String fileName = "jPostal_"+ String.format("%02d",prefCode) + ".json";
            Path dataOutputPath = outputDataDir.resolve(fileName);
            mapper.writeValue(dataOutputPath.toFile(), r.getObjects());
            
            for (int i=0; i<prefTimestamp.size(); i++) {
                if (prefTimestamp.get(i).name.equals(r.getPrefName())) {
                    prefTimestamp.remove(i);
                    break;
                }
            }
            prefTimestamp.add(
                    new PrefectureDataJsonGenerator.ResultTimestamp(r.getPrefName(), r.getDataTimestamp())
            );
        }

        Map<String, Object> data = new HashMap<>();
        data.put("lastUpdated", FORMATTER.format(ZonedDateTime.now(JST)));
        data.put("status", "OK");
        data.put("message", "Generated by Java Main method");
        
        data.put("prefectures", prefTimestamp);
        Path outputPath = outputDataDir.resolve("date.json");
        mapper.writeValue(outputPath.toFile(), data);
        System.out.println("JSONを生成しました: " + outputPath.toAbsolutePath());
        
        Path indexOutputPath = outputDir.resolve("index.html");
        try (InputStream inputStream = Main.class.getResourceAsStream("/content/index.html")) {
            if (inputStream == null) {
                throw new IOException("index.htmlが見つかりません");
            }
            Files.copy(inputStream, indexOutputPath, StandardCopyOption.REPLACE_EXISTING);
            System.out.println("index.htmlをコピーしました: " + indexOutputPath.toAbsolutePath());
        }
        Path faviconOutputPath = outputDir.resolve("favicon.png");
        try (InputStream inputStream = Main.class.getResourceAsStream("/content/favicon.png")) {
            if (inputStream == null) {
                throw new IOException("favicon.pngが見つかりません");
            }
            Files.copy(inputStream, faviconOutputPath, StandardCopyOption.REPLACE_EXISTING);
            System.out.println("favicon.pngをコピーしました: " + faviconOutputPath.toAbsolutePath());
        }

        Path masterDir = outputDataDir.resolve("master");
        if (!Files.exists(masterDir)) {
            Files.createDirectories(masterDir);
        }
        Path prefOutputPath = masterDir.resolve("pref.json");
        try (InputStream inputStream = Main.class.getResourceAsStream("/content/master/pref.json")) {
            if (inputStream == null) {
                throw new IOException("pref.jsonが見つかりません");
            }
            Files.copy(inputStream, prefOutputPath, StandardCopyOption.REPLACE_EXISTING);
            System.out.println("pref.jsonをコピーしました: " + prefOutputPath.toAbsolutePath());
        }
    }

    private static Set<PrefectureDataJsonGenerator.Result> generatePrefectureDataJson(String targetPrefecture) throws IOException {
        ObjectMapper mapper = new ObjectMapper();
        PrefectureDataJsonGenerator generator = new PrefectureDataJsonGenerator();
        Set<PrefectureDataJsonGenerator.Result> resultSet = new HashSet<>();
        boolean targetFound = targetPrefecture == null;
        
        try (InputStream inputStream = Main.class.getResourceAsStream("/content/pref.json")) {
            if (inputStream == null) { throw new IOException("pref.jsonが見つかりません"); }
            
            JsonNode rootNode = mapper.readTree(inputStream);
            if (rootNode.isArray()) {
                for (JsonNode node : rootNode) {
                    if (node.has("code") && node.has("name")) {
                        int prefCode = node.get("code").asInt();
                        String prefName = node.get("name").asString();
                        if (targetPrefecture != null
                                && !targetPrefecture.equals(prefName)
                                && !targetPrefecture.equals(String.valueOf(prefCode))
                                && !targetPrefecture.equals(String.format("%02d", prefCode))) {
                            continue;
                        }
                        targetFound = true;
                        try {
                            PrefectureDataJsonGenerator.Result result =
                                    generator.generate(prefCode, prefName);
                            System.out.println(FORMATTER.format(ZonedDateTime.now(JST)) +
                                    prefName+" 処理完了。件数: "+result.getDataSize());
                            resultSet.add(result);
                        }catch (IOException|IllegalStateException ioe) {
                            System.err.println(FORMATTER.format(ZonedDateTime.now(JST)) +
                                    node.get("name")+" 処理失敗:"+ ioe.getMessage());
                        }
                    }
                    
                }
            }
        }

        if (!targetFound) {
            throw new IllegalArgumentException("都道府県コードまたは都道府県名が不正です: " + targetPrefecture);
        }

        return resultSet;
    }
    
    private static List<PrefectureDataJsonGenerator.ResultTimestamp> loadExistPrefTimestamp(){
        List<PrefectureDataJsonGenerator.ResultTimestamp> prefectures = new ArrayList<>();

        try (HttpClient client = HttpClient.newBuilder().build()){
            HttpRequest request = HttpRequest.newBuilder()
                    .uri(URI.create("https://yui-kitamura.github.io/OsmJpPostalMapDataSource/data/date.json"))
                    .GET()
                    .build();

            HttpResponse<String> response = client.send(request, HttpResponse.BodyHandlers.ofString());

            Gson gson = new Gson();
            JsonObject jsonData = gson.fromJson(response.body(), JsonObject.class);
            JsonArray arrayData = jsonData.getAsJsonArray("prefectures");
            
            if (arrayData != null) {
                for (int i = 0; i < arrayData.size(); i++) {
                    JsonObject obj = arrayData.get(i).getAsJsonObject();
                    String name = obj.get("name").getAsString();
                    LocalDateTime timestamp = LocalDateTime.from(FORMATTER.parse(obj.get("lastModified").getAsString()));
                    prefectures.add(new PrefectureDataJsonGenerator.ResultTimestamp(name, timestamp));
                }
            }
        }catch (IOException | InterruptedException ignore) { }
        return prefectures;
    }
}
