package pro.eng.yui.android.osmjppostalmapdatasource;

import pro.eng.yui.android.osmjppostalmapdatasource.worker.PrefectureDataJsonGenerator;
import tools.jackson.databind.JsonNode;
import tools.jackson.databind.ObjectMapper;

import java.io.IOException;
import java.io.InputStream;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.nio.file.StandardCopyOption;
import java.time.ZoneId;
import java.time.ZonedDateTime;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Map;
import java.util.Set;

public class Main {
    
    public static final ZoneId JST = ZoneId.of("Asia/Tokyo");
    public static void main(String[] args) {
        System.out.println("定期実行開始: " + ZonedDateTime.now(JST));
        
        try {
            generateJson();
        } catch (IOException e) {
            System.err.println("ファイルの生成に失敗しました");
            e.printStackTrace();
        }

        System.out.println("定期実行終了: " + ZonedDateTime.now(JST));
        
    }

    private static void generateJson() throws IOException {
        ObjectMapper mapper = new ObjectMapper();
        
        // 生成するデータの基礎
        Map<String, Object> data = new HashMap<>();
        data.put("lastUpdated", ZonedDateTime.now(JST).toString());
        data.put("status", "OK");
        data.put("message", "Generated by Java Main method");

        // 保存先ディレクトリの確認
        Path outputDir = Paths.get("pages");
        if (!Files.exists(outputDir)) {
            Files.createDirectories(outputDir);
        }

        Set<PrefectureDataJsonGenerator.Result> results = generatePrefectureDataJson();
        
        // ファイル書き出し
        Path outputDataDir = outputDir.resolve("data");
        Path outputPath = outputDataDir.resolve("date.json");
        outputPath.toFile().createNewFile();
        mapper.writeValue(outputPath.toFile(), data);
        System.out.println("JSONを生成しました: " + outputPath.toAbsolutePath());
        
        for (PrefectureDataJsonGenerator.Result r : results) {
            final int prefCode = r.getPrefCode();
            final String fileName = "jPostal_"+ String.format("%02d",prefCode) + ".json";
            Path dataOutputPath = outputDataDir.resolve(fileName);
            dataOutputPath.toFile().createNewFile();
            mapper.writeValue(dataOutputPath.toFile(), r.getJsonData());
        }
        
        Path indexOutputPath = outputDir.resolve("index.html");
        try (InputStream inputStream = Main.class.getResourceAsStream("/content/index.html")) {
            if (inputStream == null) {
                throw new IOException("index.htmlが見つかりません");
            }
            Files.copy(inputStream, indexOutputPath, StandardCopyOption.REPLACE_EXISTING);
            System.out.println("index.htmlをコピーしました: " + indexOutputPath.toAbsolutePath());
        }

        Path masterDir = outputDataDir.resolve("master");
        if (!Files.exists(masterDir)) {
            Files.createDirectories(masterDir);
        }
        Path prefOutputPath = masterDir.resolve("pref.json");
        try (InputStream inputStream = Main.class.getResourceAsStream("/content/pref.json")) {
            if (inputStream == null) {
                throw new IOException("pref.jsonが見つかりません");
            }
            Files.copy(inputStream, prefOutputPath, StandardCopyOption.REPLACE_EXISTING);
            System.out.println("pref.jsonをコピーしました: " + prefOutputPath.toAbsolutePath());
        }
    }

    private static Set<PrefectureDataJsonGenerator.Result> generatePrefectureDataJson() throws IOException {
        ObjectMapper mapper = new ObjectMapper();
        PrefectureDataJsonGenerator generator = new PrefectureDataJsonGenerator();
        Set<PrefectureDataJsonGenerator.Result> resultSet = new HashSet<>();
        
        try (InputStream inputStream = Main.class.getResourceAsStream("/content/pref.json")) {
            if (inputStream == null) { throw new IOException("pref.jsonが見つかりません"); }
            
            JsonNode rootNode = mapper.readTree(inputStream);
            if (rootNode.isArray()) {
                for (JsonNode node : rootNode) {
                    if (node.has("code") && node.has("name")) {
                        PrefectureDataJsonGenerator.Result result = 
                            generator.generate(node.get("code").asInt(), node.get("name").asString());
                        resultSet.add(result);
                    }
                    
                }
            }
        }

        return resultSet;
    }
}
