package pro.eng.yui.android.osmjppostalmapdatasource;

import tools.jackson.databind.ObjectMapper;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.time.LocalDateTime;
import java.time.ZoneId;
import java.time.ZonedDateTime;
import java.util.HashMap;
import java.util.Map;

public class Main {
    public static void main(String[] args) {
        System.out.println("定期実行開始: " + ZonedDateTime.now(ZoneId.of("Asia/Tokyo")));
        
        try {
            generateJson();
        } catch (IOException e) {
            System.err.println("ファイルの生成に失敗しました");
            e.printStackTrace();
        }

        System.out.println("定期実行終了: " + ZonedDateTime.now(ZoneId.of("Asia/Tokyo")));
        
    }

    private static void generateJson() throws IOException {
        ObjectMapper mapper = new ObjectMapper();
        
        // 生成するデータの基礎
        Map<String, Object> data = new HashMap<>();
        data.put("lastUpdated", ZonedDateTime.now(ZoneId.of("Asia/Tokyo")).toString());
        data.put("status", "OK");
        data.put("message", "Generated by Java Main method");

        // 保存先ディレクトリの確認
        Path outputDir = Paths.get("pages");
        if (!Files.exists(outputDir)) {
            Files.createDirectories(outputDir);
        }

        // ファイル書き出し
        Path outputPath = outputDir.resolve("data.json");
        mapper.writeValue(outputPath.toFile(), data);
        
        System.out.println("JSONを生成しました: " + outputPath.toAbsolutePath());
    }
}
